#公用配置
spring.application.name=medical-data-transfer-service

#数据源
spring.datasource.driver-class-name=org.postgresql.Driver
#ceshi
spring.datasource.url=jdbc:postgresql://20.240.39.69:5432/ptransfer001db
#dingban
#spring.datasource.url=jdbc:postgresql://20.200.35.148:5432/transfer
#shengchan
#spring.datasource.url=jdbc:postgresql://22.240.133.117:5432/transfer

spring.datasource.username=transfer
spring.datasource.password=ENC(rhhfnPRhoh5pm5ndc7eKtgn7RP+cVlcv)
#加密所需的salt(盐)
jasyp.encryptor.password=lQaz0oKm
# 默认加密方式PBEWithMD5AndDES,可以更改为PBEWithMD5AndTripleDES
jasyp.encryptor.algorithm=PBEWithMD5AndDES

#医疗数据交换（EDB）配置
#系统密钥
sys.key=
046308637690f356dfd3f25212d9eb258d1bc6d3e633c5e84721f94dcbbb518f4ec13da2f2942686f223fc22a9e475e
920812a8d2e35f23a57fb708af495863d56ac947d43b576e2d839e37609af327eb6a53ab62933b929c69b77bf6288cb
9716fe7813d0914e91cb6851355ef15ef5bf8f16
#医疗数据交换客户端urls
edbClient.urls=http://20.240.39.81:9021,http://20.240.39.82:9021
#文件上传
uploadFiles.interface=/api/edb/client/actions/uploadFiles
#1-文件路径方式上传，0-文件流方式上传
uploadFiles.stream.status=1
#EDB系统号
edb.sys.code=99710930001
#下载接口名
DownloadFiles.interface=/api/edb/client/actions/DownloadFiles
#文件下载方式 1 通过文件流形式 0 文件形式，下载至客户端服务器
receiveFile.stream.status=0
#自动接收消息回执的接口名
autoReceiveMessage.interface=/api/edb/client/actions/receiveMessagesAutoAck
#非自动回执接收消息的接口名
receiveMessage.interface=/api/edb/client/actions/receiveMessages
#回执接口
ackMessage.interface=/api/edb/client/actions/ackMessages
#是否自动回执接口
is.autoReceiveMessage=0
#文件服务主中心
file.mainCenter.code=HF
#接收方系统号
recv.sys.code=99710930001
server.name=server1
dest.name=dest1
id_rsa
privatekey.path=/app/appedb/.ssh/id_rsa
#sftp
sftp.name=appedb
#探测接口
checklist.interface=/api/edb/client/plugin/list
#mybatis
mybatis.mapper-locations=classpath*:mapper/*Mapper.xml
mybatis.type-aliases-package=com.transfer.medical.pojo

#filesize uploadfile
spring.servlet.multipart.max-file-size=1500MB
spring.servlet.multipart.max-request-size=1500MB
spring.servlet.multipart.file-size-threshold=20MB
#server.tomcat.max-http-post-size=104857600
#server.jetty.max-http-post-size=104857600
server.tomcat.connection-timeout=600000
server.tomcat.keep-alive-timeout=60000



#线程池
##核心线程数
spring.task.execution.pool.core-size=5
##最大线程数
spring.task.execution.pool.max-size=5
##线程队列数量
spring.task.execution.pool.queue-capacity=9999
##线程名称前缀
spring.task.execution.thread-name-prefix=MEDICAL-TASK-
##是否允许核心线程超时
spring.task.execution.pool.allow-core-thread-timeout=true
#定时任务
spring.task.scheduling.pool.size=10
spring.task.scheduling.thread-name-prefix=MEDICAL-SCHEDULING-TASK-
#定时任务参数
#下载
scheduled.task.download.initialDelay=5000
scheduled.task.download.fixedRate=60000
#处理
scheduled.task.process.initialDelay=5000
scheduled.task.process.fixedRate=60000
#接收消息
scheduled.task.receive.initialDelay=5000
scheduled.task.receive.fixedRate=5000
#下发文件
scheduled.task.push.initialDelay=5000
scheduled.task.push.fixedRate=60000
#检查文件是否收齐
scheduled.task.check.initialDelay=5000
scheduled.task.check.fixedRate=60000
#清理过期文件
scheduled.task.cleanup.initialDelay=5000
scheduled.task.cleanup.fixedRate=60000
#发送到hdfs
scheduled.task.sendhdfs.initialDelay=5000
scheduled.task.sendhdfs.fixedRate=60000
#失败重试
scheduled.task.try.initialDelay=5000
scheduled.task.try.fixedRate=60000
#监控线程池
scheduled.task.monitor.initialDelay=5000
scheduled.task.monitor.fixedRate=60000
#下载Verify
scheduled.task.downloadvery.initialDelay=5000
scheduled.task.downloadvery.fixedRate=60000
#探测接口
scheduled.task.checklist.initialDelay=5000
scheduled.task.checklist.fixedRate=60000


