#data.share.download.dir.prefix=/app/co_etp/co_etp_data
#task.upload.local.path.prefix=/app/co_etp
#ceshi
#data.share.download.dir.prefix=/app/transfer/transfile
#dingban and shengchan
data.share.download.dir.prefix=/transfer/transfile
task.upload.local.path.prefix=/user/hdfs/transfile/
send.hdfs.delete.src.flag=false
is.need.ha=1
delete.local.data.interval=365
ftp.tools.path=~/client.jar
#1:command 0:sftp
download.method=1
set.complete.time=00:00:00
# 1(enable) 0(disable)
enable.drop.duplicated.message=1
# 1(enable) 0(disable)
enable.check.customer.market.data=1
#threshold
check.threshold=0
#=================================================hadoop=================================================
#dingban
hadoop.name.node=hdfs://namenodeHA
hadoop.username=hdfs
hadoop.name.host1=mpmhp1:8020
hadoop.name.host2=mpmhp2:8020
#shengchan
hadoop.name.host1=mpmhdn1:8020
hadoop.name.host2=mpmhdn2:8020
#ceshi

#hadoop.name.host1=mpm-dev-hp01:8020
#hadoop.name.host2=mpm-dev-hp02:8020
hadoop.krb.path=/etc/krb5.conf
hadoop.principal.name=hdfs-hadoop_dev_mpm@MPM.COM
hadoop.keytab.path=/etc/security/keytabs/hdfs.headless.keytab
#=================================================medical data exchange url=================================================
#ceshi
EdbClient.Urls=http://20.240.39.81:9021,http://20.240.39.82:9021
receiveMessagesAutoAck.interface=/api/edb/client/actions/receiveMessagesAutoAck
uploadFiles.interface=/api/edb/client/actions/uploadFiles
DownloadFiles.interface=/api/edb/client/actions/DownloadFiles
serverName=server1
recvSysCode=99710930001
sysKey=
046308637690f356dfd3f25212d9eb258d1bc6d3e633c5e84721f94dcbbb518f4ec13da2f2942686f223fc22a9e475e
920812a8d2e35f23a57fb708af495863d56ac947d43b576e2d839e37609af327eb6a53ab62933b929c69b77bf6288cb
9716fe7813d0914e91cb6851355ef15ef5bf8f16
fileMainCenterCode=HF
receiveFileStreamStatus=0
#===================================sftp===================================
#sftp.username=spark
sftp.password=spark
sftp.port=22
sftp.host=20.200.35.226
sftp.temp.dir.prefix=/app
#===================================client===================================
#client.username=spark
client.password=spark
client.host=20.200.35.226
client.temp.dir.prefix=/app/data/customer-market
#===================================zookeeper===================================
#shengchan
zookeeper.server=22.241.109.41:2181,22.241.109.42:2181,22.241.109.43:2181
#dingban
#zookeeper.server=20.201.35.174:2181,20.201.35.175:2181,20.201.35.176:2181
#ceshi
#zookeeper.server=20.200.35.131:2181,20.200.35.132:2181,20.200.35.133:2181
zookeeper.sessionTimeoutMs=6000
zookeeper.connectionTimeoutMs=6000
zookeeper.maxRetries=3
zookeeper.baseSleepTimeMs=1000
zookeeper.path=/leader
zookeeper.namespace=co_transfer
zookeeper.namespace=transfer
#===================================check 10 interface===================================
#interface.check.ten=BONDDT,JJTGR,FUNDTYPES,FINFO,NAV,NAV_CUR,NEWSTEXT,NEWSTYPE,NEWSINDUS,NEWSFIN,NEWSAUTH,CFPPROFILE\
,TQ_FD_ASSETPORTFOLIO,TQ_FD_BDDETAIL,TQ_FD_SKDETAIL,TQ_FD_MGPERFORMANCE,FUNDMG,OFPROFILE,CHGR
#interface.check.ten=BONDDT,FINFO,NAV,NAV_CUR,NEWSTEXT,NEWSTYPE,NEWSINDUS,NEWSFIN,NEWSAUTH,CFPPROFILE\
,TQ_FD_ASSETPORTFOLIO,TQ_FD_BDDETAIL,TQ_FD_SKDETAIL,TQ_FD_MGPERFORMANCE
#========================通过Verify文件进行文件个数校验========================
#interface.check.many=99550000000_GESSPSEBC-T_RGS_PRODUCT_0000
#===================通过消息头中的文件数进行文件个数校验，有Verify的优先使用Verify检查==================
#interface.fileenum.check.many=99711400000_CRDT_ISSU_BIZ_STATS_MEM_0000,99711400000_CRDT_USE_SITU_STATS_MEM_0000

#===================部分系统文件名中没有发送方系统编码，单独映射处理==================
interface.filename.syscode.map=
{"99710940000_611110":"99700060000","99100040000_TEL_TXN_CSTM_INFO":"93307000000","99100040000_TEL_TXN_TYPE_DEF":"93307000000","99100050000_TV_TXN_TYPE_DEF":"93307000000"}

#========================忽略重复发送的系统号=======================
#interface.ignore.repeat.syscode=99710950000,99711400000

#===================部分文件无法通过探测获取文件类型，手动映射==================
interface.filepath.filecode.map=
{"99700050000_JGQL_0000":"GB18030","99700060000_99710930000_611120_1100":"GB18030","99700060000_611170_1100":"GB18030","99700060000_99710900000_611120_1100":"GB18030","99370000000_JJFZ09_0000":"GB18030","99400000000_CPAI-SMCTL_INSU_KIND_CODE_0000":"GB18030","99400000000_CPAI-SMCTL_INSU_PROD_CODE_0000":"GB18030","99400000000_CPAI-BORGT_POL_0000":"GB18030","99400000000_CPAI-BORGT_JMGH_INFO_0000":"GB18030","99400000000_CPAI-SMCTL_INSU_CODE_0000":"GB18030","99550000000_TRADE_INFO_REALTIME_0000":"GB18030","99550000000_GESSPSEBC-T_RGS_PRODUCT_0000":"GB18030"}
#对公
#task.process.hdfs.path.prefix=/user/hdfs/co_transfer
task.process.hdfs.path.prefix=/user/hdfs
