#dingban
#消息服务器ip(主备，实际生产根据所在中心进行配置)
server1.url=20.198.34.150:5672
#虚拟主机（必填）
server1.vhost=/
#本用户的系统号。
server1.username=99710930000
#本用户密码
server1.password=emhqeWp4
server1.dest1=QM.99710930000.01.Medical.000000

#EDB-2022年新增
#服务端地址
server1.con_url=http://20.198.34.152:7006
#http连接超时
server1.con_url.http_conn_timeout=5000
#从http连接池获取资源超时
server1.con_url.http_conn_re_timeout=1000
#从http读取资源超时
server1.con_url.so_timeout=5000
#存放缓存文件目录(需要对本用户有读写权限)
server1.cache_dir=/app/transfer/msgtmp

#yuyan
#消息服务器ip(主备，实际生产根据所在中心进行配置)
#server1.url=20.198.34.154:5672
##虚拟主机（必填）
#server1.vhost=/
##本用户的系统号。
#server1.username=99710930000
##本用户密码
#server1.password=emhqeWp4
#server1.dest1=QM.99710930000.01.Medical.000000
#EDB-2022年新增
#服务端地址
#server1.con_url=http://20.198.34.156:7006
##http连接超时
#server1.con_url.http_conn_timeout=5000
##从http连接池获取资源超时
#server1.con_url.http_conn_re_timeout=1000
##从http读取资源超时
#server1.con_url.so_timeout=5000
##存放缓存文件目录(需要对本用户有读写权限)
#server1.cache_dir=/app/mpm/transfer/new transfer/msgtmp


#shengchan
#消息服务器ip(主备，实际生产根据所在中心进行配置)
#server1.url=22.225.32.72:5672,22.225.32.73:5672,22.242.66.6:5672,22.242.66.7:5672,22.200.209.200:5672,22.200.209.201:5672
##虚拟主机（必填）
server1.vhost=/
##本用户的系统号。
server1.username=99710930000
##本用户密码
server1.password=emh5eDB6aHl4
server1.dest1=QM.99710930000.01.Medical.000000
#EDB-2022年新增
#服务端地址
#server1.con_url=http://22.225.32.86:7005,http://22.242.66.44:7005,http://22.200.209.214:7005
#http连接超时
#server1.con_url.http_conn_timeout=5000
#从http连接池获取资源超时
#server1.con_url.http_conn_re_timeout=1000
#从http读取资源超时
#server1.con_url.so_timeout=5000
##存放缓存文件目录(需要对本用户有读写权限)
#server1.cache_dir=/app/mpm/transfer/new transfer/msgtmp

