#EDB2.0
#EDB dingban
#管控地址(主备，根据本用户所在中心进行分配)
server1.server_con_url=http://20.198.34.152:7006
#一期传输服务地址
server1.server_url=tcp://20.200.42.31:10001
#一期二期共用 文件传输所需要的临时目录路径（绝对路径）
server1.EFTP_LOCATION=/app/transfer/transfer_log
#本用户系统号 一期二期共用
server1.sys_code=99710930000
server1.password1=emhqeWp4
#上传超时时间(单位毫秒) 一期二期共用
server1.put_timeout=100000
#下载超时时间(单位毫秒) 一期二期共用
server1.remote_get_timeout=1000000
#一期特有
server1.open_timeout=10000
#一期特有
server1.get_Notice_timeout=10000
#二期特有(断点续传标志，1表示开启)
server1.ddxc_flag=1
#一期特有(默认)
server1.hostid=000
#一期特有(默认)
server1.cmp_size=10
#重发次数(文件发送失败，自动重发文件，最小重发1次，最大重发5次，建议开启)
server1.resend_num=2

#EDB yuyan
#管控地址(主备，根据本用户所在中心进行分配)
#server1.server_con_url=http://20.198.34.156:7006
##一期传输服务地址
#server1.server_url=tcp://20.200.42.32:10001
##一期二期共用 文件传输所需要的临时目录路径（绝对路径）
#server1.EFTP_LOCATION=/app/mpm/transfer/new transfer/transfer_log
##本用户系统号 一期二期共用
#server1.sys_code=99710930000
#server1.password1=emhqeWp4
#server1.password1=zhjyjx
##上传超时时间(单位毫秒) 一期二期共用
#server1.put_timeout=100000
##下载超时时间(单位毫秒) 一期二期共用
#server1.remote_get_timeout=1000000
##一期特有
#server1.open_timeout=10000
##一期特有
#server1.get_Notice_timeout=10000
##二期特有(断点续传标志，1表示开启)
#server1.ddxc_flag=1
##一期特有(默认)
#server1.hostid=000
##一期特有(默认)
#server1.cmp_size=10
##重发次数(文件发送失败，自动重发文件，最小重发1次，最大重发5次，建议开启)
#server1.resend_num=2

#shengchan
#管控地址(主备，根据本用户所在中心进行分配)
#server1.server_con_url=http://22.225.32.86:7005,http://22.242.66.44:7005,http://22.200.209.214:7005
##一期传输服务地址
server1.server_url=tcp://22.246.2.230:9001,tcp://22.246.2.230:9002
##一期二期共用 文件传输所需要的临时目录路径（绝对路径）
server1.EFTP_LOCATION=/app/mpm/transfer/new transfer/transfer_log
##本用户系统号 一期二期共用
server1.sys_code=99710930000
server1.password1=emh5eDB6aHl4
##上传超时时间(单位毫秒) 一期二期共用
server1.put_timeout=180000
##下载超时时间(单位毫秒) 一期二期共用
server1.remote_get_timeout=850000
##一期特有
server1.open_timeout=10000
##一期特有
server1.get_Notice_timeout=10000
##二期特有(断点续传标志，1表示开启)
server1.ddxc_flag=1
##一期特有(默认)
server1.hostid=000
##一期特有(默认)
server1.cmp_size=10
##重发次数(文件发送失败，自动重发文件，最小重发1次，最大重发5次，建议开启)
server1.resend_num=2

#新版jar包多了http请求超时设置(单位毫秒，用给出的值即可)
#http连接超时
server.conn_timeout=5000
#从http连接池获取资源超时
server.conn_re_timeout=1000
#从http读取资源超时
server.so_timeout=10000
